### ISSUE TITLE
Bundle exec anycable failed to load command

### ISSUE THREAD

**Issue by kcrwfrd** [anycable/anycable#231]
### Tell us about your environment

**Ruby version:**
`ruby 3.2.3 (2024-01-18 revision 52bb2ac0a6) [arm64-darwin22]`

**`anycable` gem version:**
`gem 'anycable-rails', '1.5'`

**`grpc` gem version:**
`grpc-1.62.0-arm64-darwin`

### What did you do?
```
# in project directory
bundle install
bundle exec anycable
```

### What did you expect to happen?
Expected command to run AnyCable RPC server

### What actually happened?
```
❯ bundle exec anycable
bundler: failed to load command: anycable (/Users/kevin.crawford/.rbenv/versions/3.2.3/bin/anycable)
/Users/kevin.crawford/.rbenv/versions/3.2.3/bin/anycable:25:in `load': cannot load such file -- /Users/kevin.crawford/.gem/ruby/3.2.0/specifications/bin/anycable (LoadError)
	from /Users/kevin.crawford/.rbenv/versions/3.2.3/bin/anycable:25:in `<top (required)>'
	from /Users/kevin.crawford/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/bundler-2.4.2/lib/bundler/cli/exec.rb:58:in `load'
	from /Users/kevin.crawford/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/bundler-2.4.2/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /Users/kevin.crawford/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/bundler-2.4.2/lib/bundler/cli/exec.rb:23:in `run'
	from /Users/kevin.crawford/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/bundler-2.4.2/lib/bundler/cli.rb:491:in `exec'
	from /Users/kevin.crawford/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/bundler-2.4.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Users/kevin.crawford/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/bundler-2.4.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/kevin.crawford/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/bundler-2.4.2/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /Users/kevin.crawford/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/bundler-2.4.2/lib/bundler/cli.rb:34:in `dispatch'
	from /Users/kevin.crawford/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/bundler-2.4.2/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /Users/kevin.crawford/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/bundler-2.4.2/lib/bundler/cli.rb:28:in `start'
	from /Users/kevin.crawford/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/bundler-2.4.2/exe/bundle:45:in `block in <top (required)>'
	from /Users/kevin.crawford/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/bundler-2.4.2/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from /Users/kevin.crawford/.rbenv/versions/3.2.3/lib/ruby/gems/3.2.0/gems/bundler-2.4.2/exe/bundle:33:in `<top (required)>'
	from /Users/kevin.crawford/.rbenv/versions/3.2.3/bin/bundle:25:in `load'
	from /Users/kevin.crawford/.rbenv/versions/3.2.3/bin/bundle:25:in `<main>'
```

**Comment by palkan** [comment]
Could you please show the contents of the `/Users/kevin.crawford/.rbenv/versions/3.2.3/bin/anycable` file? 

The `.gem/ruby/3.2.0/specifications/bin/anycable` line looks suspicious. Probably. something `rbenv` related? 

My backtrace looks like this (and I expect `anycable-1.5.0` to be in the stack trace):

```
...
"/opt/homebrew/lib/ruby/gems/3.2.0/gems/anycable-core-1.5.0/bin/anycable:4:in `<top (required)>'",
 "/opt/homebrew/lib/ruby/gems/3.2.0/bin/anycable:25:in `load'",
...
 ```

**Comment by kcrwfrd** [comment]
I actually just ended up getting this working. The path in `/Users/kevin.crawford/.gem/ruby/3.2.0/specifications/bin/anycable` was suspicious to me as well—why was it referencing `$HOME/.gem` when I was using rbenv, and expected everything to be installed within `$HOME/.rbenv`?

I removed the `$HOME/.gem` directory completely, and `bundle exec anycable` started working for me.

I think the `.gem` directory had been added when installing some VS Code Ruby extensions. I may have installed them before I had installed `rbenv`, because I just tried uninstalling and then reinstalling all of my Ruby extensions and it did not make the directory re-appear.

For posterity's sake, here's the contents of `~/.rbenv/versions/3.2.3/bin/anycable`:

```ruby
#!/usr/bin/env ruby
#
# This file was generated by RubyGems.
#
# The application 'anycable-core' is installed as part of a gem, and
# this file is here to facilitate running it.
#

require 'rubygems'

Gem.use_gemdeps

version = ">= 0.a"

str = ARGV.first
if str
  str = str.b[/\A_(.*)_\z/, 1]
  if str and Gem::Version.correct?(str)
    version = str
    ARGV.shift
  end
end

if Gem.respond_to?(:activate_bin_path)
load Gem.activate_bin_path('anycable-core', 'anycable', version)
else
gem "anycable-core", version
load Gem.bin_path("anycable-core", "anycable", version)
end
```

Than you for taking a look.

**Comment by palkan** [comment]
Thanks for the details! That will help others to resolve similar issues.
