### ISSUE TITLE
Exception while handling disconnection of connection with multiple channels

### ISSUE THREAD

**Issue by Envek** [anycable/anycable#51]
I have a problem when handling disconnection (closed browser tab) from connection with three channels being connected to.

As it can be seen from logs, `anycable-go` server sends disconnection request for three channels with ids `165d8949069`, `165d8941e62`, `165d8942db1`:
```
map[{"channel":"GraphqlChannel","channelId":"165d8949069"}:true {"channel":"GraphqlChannel","channelId":"165d8941e62"}:true {"channel":"GraphqlChannel","channelId":"165d8942db1"}:true]
```
but RPC server receives only data for one of them (`165d8942db1`) and empty strings for others:
```
subscriptions: ["{\"channel\":\"GraphqlChannel\",\"channelId\":\"165d8942db1\"}", "", ""]
```

which causes ActionCable internals to fail here with exception `An empty string is not a valid JSON string.`:

https://github.com/rails/rails/blob/375a4143cf5caeb6159b338be824903edfd62836/actioncable/lib/action_cable/connection/subscriptions.rb#L27-L29

I've compared protobuf declarations for anycable-go and anycable gem and they seem to match: both declare subscriptions as `repeatable string`.

Have no idea about where these empty strings are coming from.

Logs:
```
anycable  |  DEBUG 2018-09-14T14:54:47.805Z context=node sid=zkAaDO9AVIE4Z05TK8vt8u websocket session completed
anycable  |  DEBUG 2018-09-14T14:54:47.805Z channel={"channel":"GraphqlChannel","channelId":"165d8949069"} context=hub sid=zkAaDO9AVIE4Z05TK8vt8u Unsubscribed             
anycable  |  DEBUG 2018-09-14T14:54:47.805Z channel={"channel":"GraphqlChannel","channelId":"165d8941e62"} context=hub sid=zkAaDO9AVIE4Z05TK8vt8u Unsubscribed             
anycable  |  DEBUG 2018-09-14T14:54:47.805Z channel={"channel":"GraphqlChannel","channelId":"165d8942db1"} context=hub sid=zkAaDO9AVIE4Z05TK8vt8u Unsubscribed             
anycable  |  DEBUG 2018-09-14T14:54:47.805Z context=hub sid=zkAaDO9AVIE4Z05TK8vt8u Unregistered             
anycable  |  DEBUG 2018-09-14T14:54:47.805Z context=node sid=zkAaDO9AVIE4Z05TK8vt8u Disconnect {"account":"Z2lkOi8vZWJheS1tYWcyL0FjY291bnQvMQ"} /cable?token=jwt map[cookie:cookie] map[{"channel":"GraphqlChannel","channelId":"165d8949069"}:true {"channel":"GraphqlChannel","channelId":"165d8941e62"}:true {"channel":"GraphqlChannel","channelId":"165d8942db1"}:true]
rpc       | RPC Disconnect: <Anycable::DisconnectRequest: identifiers: "{\"account\":\"Z2lkOi8vZWJheS1tYWcyL0FjY291bnQvMQ\"}", subscriptions: ["{\"channel\":\"GraphqlChannel\",\"channelId\":\"165d8942db1\"}", "", ""], path: "/cable?token=jwt", headers: {"cookie"=>"cookie"}>
rpc       | An empty string is not a valid JSON string.
anycable  |  DEBUG 2018-09-14T14:54:47.810Z context=rpc Disconnect response: error_msg:"An empty string is not a valid JSON string." 
anycable  |  ERROR 2018-09-14T14:54:47.811Z context=node sid=zkAaDO9AVIE4Z05TK8vt8u Disconnect error: Application error: An empty string is not a valid JSON string.
```

Backtrace:
```
 0: /home/envek/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.1/lib/active_support/json/decoding.rb:23:in `parse'
 1: /home/envek/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/activesupport-5.2.1/lib/active_support/json/decoding.rb:23:in `decode'
 2: /home/envek/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/actioncable-5.2.1/lib/action_cable/connection/subscriptions.rb:29:in `add'
 3: /home/envek/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/anycable-rails-0.5.4/lib/anycable/rails/refinements/subscriptions.rb:9:in `fetch'
 4: /home/envek/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/anycable-rails-0.5.4/lib/anycable/rails/actioncable/connection.rb:40:in `block in initialize'
 5: /home/envek/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/anycable-rails-0.5.4/lib/anycable/rails/actioncable/connection.rb:40:in `each'
 6: /home/envek/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/anycable-rails-0.5.4/lib/anycable/rails/actioncable/connection.rb:40:in `initialize'
 7: /home/envek/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/anycable-rails-0.5.4/lib/anycable/rails/actioncable/connection.rb:17:in `new'
 8: /home/envek/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/anycable-rails-0.5.4/lib/anycable/rails/actioncable/connection.rb:17:in `call'
```

anycable-go 0.6.0 built from master.
gem anycable 0.5.2
gem anycable-rails 0.5.4
Ruby on Rails 5.2.1
gem grpc 1.15.0-x86_64-linux
gem google-protobuf 3.6.1 from master at ff3891dab1b1

**Comment by palkan** [comment]
I've tried to reproduce but without any luck so far(

Added a unit-test [here](https://github.com/anycable/anycable-go/commit/0acba343c5469edf2dc9b824bf6e03f6c7732299) and integrations tests [here](https://github.com/anycable/anyt/blob/master/lib/anyt/tests/request/disconnection_test.rb). No failures.

I've also updated logging for `Disconnect` call in `anycable-go` to show the resulted subscriptions list instead of the original one (https://github.com/anycable/anycable-go/commit/8e38d1bf51485266f0aaf1745cf9a5228ac9c310). Let's try to debug it.
